### ISSUE TITLE
滴滴招聘，是否愿意给个简历？

### ISSUE THREAD

**Issue by taowen** [zieckey/interview#5]
滴滴专快车系统肩负着上亿用户和几千万司机间的供需匹配，每天上 1000w 订单，每个订单涉及到几十上百个状态的实时维护。高可用，是对用户和司机权益的基本保证，也是挑战和艺术。您将负责专快车从用户接入到数据存储的高可用方案的设计和实现

taowen@didichuxing.com

**Comment by zieckey** [comment]
谢谢。暂时不感兴趣。
